### PR TITLE
add support for Venu 2 plus

### PR DESCRIPTION
**Pull request by mario-s**
This small app makes a lot of sense when it runs on a watch. So I added support for a newer device Garmin Venu 2 Plus, hoping that this will make it into the master and to the store. I was just not sure where to set a new version.

### CODE REVIEW

**Comment by mario-s** [comment]
No progress here.

**Comment by klimeryk** [comment]
@mario-s, thanks for your PR! Sorry I was not able to react it on time - Garmin always surprises me with a dump of new devices 😅 I'ved added Venu 2 Plus (and other new devices) in https://github.com/klimeryk/garmodoro/commit/5b1ec75b1fe3da3e683cb30998d614bec19e9091 (version 1.8.3 in Connect IQ). I've just uploaded it to Connect IQ - it should be available within 2 hours 🙇

**Comment by mario-s** [comment]
@klimeryk thanks a lot for the reply! I fully understand that you might be overwhelmed with all the devices, especially when it is only a sight project. I was just a bit worried because some PRs were quite old. I hope it is ok, if I took your code a foundation for my own app. It is actually a lot of fun programming with Monkey_C and see the app on the watch.

**Comment by klimeryk** [comment]
No worries! Yeah, I've not had too much time to invest in this project lately (and it's been working well as-is for me, so even less motivation).
No issue with basing a new app on my code! That's why I open-sourced it :) I assume it's this project: https://github.com/mario-s/pomodoro-timer.

However, one thing I need to note is that this code is licensed under GPLv3. And [one of the requirements is to use the same license for any derivative work](https://choosealicense.com/licenses/gpl-3.0/). Could you change the license to GPLv3 as well? It's not a huge issue and I don't think it changes much - except that any derivative work of _your_ app would have to use GPLv3 as well. In that sense, it's a "viral" license. Which is good for the open-source community :)

Also, curious to hear how you want to improve the code! If I know you're active and motivated to work on this project, I'm happy to prioritize any PRs from you and review them in a timely manner. It seems you want to drop support for the handheld devices? That will definitely give some extra flexibility for visuals, but with the way Connect IQ SDK works, I guess the UI could be tweaked to be different for each device, while still retaining the same "backend".

Anyway, let me know if you want to collaborate on this project. But also fully supportive of creating your own version! 🙌

**Comment by mario-s** [comment]
Indeed, it is the one which you mentioned above. I thiught I could go with APL 2.0 since I read somewhere that this is an appropriate license for smaller projects, but did not know that GPLv2 is so viral. Anyway, I will change it.

Indeed the app makes a lot of sense when you have it on the watch. For instance when working from home you may not get up from the desk for hours, this little thing on your wrist reminds you to take a break. 

I'd like to have a progress bar as a circle on the ui, another feetback how much time is left. Also some more vibrations 3 seconds before the end of an interval.

**Pull request closed without merging**
